### ISSUE TITLE
Generated target path 

### ISSUE THREAD

**Issue by neel** [Klebert-Engineering/python-cmake-wheel#11]
I am looking for a variable that contains the generated target path.

There is PY_WHEEL_C_INFIX. But I guess that is only the suffix.

**Comment by josephbirkner** [comment]
The final name is decided by the Python wheel package. I would recommend to just iterate over the contents of `WHEEL_DEPLOY_DIRECTORY` (this is how we do it).

**Comment by neel** [comment]
I see. I thought PY_WHEEL_C_INFIX would be same as the name decided by the Python wheel package. Is there any python command that can be invoked from cmake to determine the name in advance ?

**Comment by josephbirkner** [comment]
This should work: `${WHEEL_DEPLOY_DIRECTORY}/${WHEEL_NAME}-${WHEEL_VERSION}${PY_WHEEL_C_INFIX}.whl`
